### ISSUE TITLE
[PE-D] Potential bug 6: Insertion of exercises in the upcoming exercise list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-F14-2/tp#204]
As shown below, the same exercise records (same name, same date, same calories, same time) are inserted even though they exist in the upcoming exercise list. For example, I inserted "running" for every day in November, but I can still insert the same data repeatedly. So in total, I have 44 records, but in fact I should only have 30 records. (For each day in November). 

Possible suggestions: It would be better if you specify the time of the exercise in case that you allow the same exercise to appear repeatedly in a day.

![bug6.png](https://raw.githubusercontent.com/KairuiHu/ped/main/files/f646b856-d40f-42af-b23e-5eb3f03230c8.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: KairuiHu/ped#6

**Comment by weidak** [comment]
We believe that our current implementation is fine because you are able to do multiple exercises in a day, and that the value of the time of exercise does not really matter so long as you perform the exercise on the day itself. For instance, you can have multiple runs scheduled for tomorrow itself, and it may be up to you to name the distance/type of run you might be doing.
